version: '3'

services:
  db-investimento:
    container_name: db-investimento
    image: postgres:15.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  api-investimento:
    build: .
    ports:
      - 3001:3001
    environment:
      - DB_HOST=db-investimento
    depends_on:
      - db-investimento
